services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./Backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./Frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules: